# Shell variables
# Generated by 'wal'
wallpaper='/home/mantas/Desktop/jackson-hendry-eodA_8CTOFo-unsplash.jpg'

# Special
background='#020306'
foreground='#a6abc2'
cursor='#a6abc2'

# Colors
color0='#020306'
color1='#334575'
color2='#464E75'
color3='#483B96'
color4='#375087'
color5='#376593'
color6='#495788'
color7='#a6abc2'
color8='#747787'
color9='#334575'
color10='#464E75'
color11='#483B96'
color12='#375087'
color13='#376593'
color14='#495788'
color15='#a6abc2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
