--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mantas/Desktop/jackson-hendry-eodA_8CTOFo-unsplash.jpg"

-- Special
background="#020306"
foreground="#a6abc2"
cursor="#a6abc2"

-- Colors
color0="#020306"
color1="#334575"
color2="#464E75"
color3="#483B96"
color4="#375087"
color5="#376593"
color6="#495788"
color7="#a6abc2"
color8="#747787"
color9="#334575"
color10="#464E75"
color11="#483B96"
color12="#375087"
color13="#376593"
color14="#495788"
color15="#a6abc2"
